apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: ispn-host
  namespace: infinispan
spec:
  replicas: 3
  version: 16.0.8
  service:
    type: DataGrid
    container:
      extraJvmOpts: >-
        -Dinfinispan.cluster.stack=kubernetes
        -Djgroups.dns.query=ispn-host-ping.infinispan.svc.cluster.regiontwo
  security:
    endpointSecretName: ispn-credentials
