apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: ispn-host
  namespace: infinispan
spec:
  replicas: 3
  version: 16.0.8
  container:
    extraJvmOpts: >-
      -Dinfinispan.cluster.stack=kubernetes
      -Djgroups.dns.query=ispn-host-ping.infinispan.svc.cluster.regiontwo
  service:
    type: DataGrid
    container:
      storage: 2Gi
      storageClassName: general
  security:
    endpointSecretName: ispn-credentials
