apiVersion: v1
kind: Secret
metadata:
  name: ispn-credentials
  namespace: infinispan
type: Opaque
stringData:
  identities.yaml: |-
    credentials:
      - username: admin
        password: devSTACK1!
        roles:
          - admin
