apiVersion: v1
kind: ServiceAccount
metadata:
  name: ispn-pipeline
  namespace: kubesphere-devops-worker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ispn-pipeline-role
  namespace: infinispan
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - delete

  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - patch

  - apiGroups: ["infinispan.org"]
    resources:
      - infinispans
      - caches
      - batches
      - backups
      - restores
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["infinispan.org"]
    resources:
      - infinispans/status
      - caches/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ispn-pipeline-rolebinding
  namespace: infinispan
subjects:
  - kind: ServiceAccount
    name: ispn-pipeline
    namespace: kubesphere-devops-worker
roleRef:
  kind: Role
  name: ispn-pipeline-role
  apiGroup: rbac.authorization.k8s.io
